-- Schema iniziale per la feature Clienti.
-- Pensato per Apache Derby: gli UUID vengono salvati come CHAR(36) e generati dall'applicazione.
-- Il file non usa CREATE TABLE IF NOT EXISTS perché Derby non lo supporta in modo portabile.

CREATE TABLE OPERATORI (
    ID CHAR(36) NOT NULL,
    NOME VARCHAR(120),
    COGNOME VARCHAR(120),
    USERNAME VARCHAR(80),
    ATTIVO SMALLINT DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_OPERATORI PRIMARY KEY (ID),
    CONSTRAINT UQ_OPERATORI_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_OPERATORI_ATTIVO CHECK (ATTIVO IN (0, 1))
);


CREATE TABLE TIPI_CLIENTE (
    ID CHAR(36) NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    ORDINE INTEGER DEFAULT 0,
    CONSTRAINT PK_TIPI_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT UQ_TIPI_CLIENTE_NOME UNIQUE (NOME)
);


CREATE TABLE STATI_TRATTATIVA (
    ID CHAR(36) NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    ORDINE INTEGER DEFAULT 0,
    CONSTRAINT PK_STATI_TRATTATIVA PRIMARY KEY (ID),
    CONSTRAINT UQ_STATI_TRATTATIVA_NOME UNIQUE (NOME)
);

CREATE TABLE FORNI (
    ID CHAR(36) NOT NULL,
    TECNOLOGIA VARCHAR(120) NOT NULL,
    MARCA VARCHAR(120) NOT NULL,
    MODELLO VARCHAR(120) NOT NULL,
    CONSTRAINT PK_FORNI PRIMARY KEY (ID)
);

CREATE TABLE FRESATORI (
    ID CHAR(36) NOT NULL,
    MARCA VARCHAR(120) NOT NULL,
    MODELLO VARCHAR(120) NOT NULL,
    CONSTRAINT PK_FRESATORI PRIMARY KEY (ID)
);

CREATE TABLE CANALI_DI_ACQUISTO (
    ID CHAR(36) NOT NULL,
    MODALITA VARCHAR(120) NOT NULL,
    NOTA VARCHAR(500),
    CONSTRAINT PK_CANALI_DI_ACQUISTO PRIMARY KEY (ID)
);

CREATE TABLE MATERIALI_DI_CONSUMO (
    ID CHAR(36) NOT NULL,
    MATERIALE VARCHAR(120) NOT NULL,
    MARCHIO VARCHAR(120) NOT NULL,
    MODELLO VARCHAR(120) NOT NULL,
    CONSTRAINT PK_MATERIALI_DI_CONSUMO PRIMARY KEY (ID)
);

CREATE TABLE CLIENTI (
    ID CHAR(36) NOT NULL,
    RAGIONE_SOCIALE VARCHAR(255),
    TIPO_CLIENTE VARCHAR(40),
    STATO_TRATTATIVA VARCHAR(40),
    COINVOLGIMENTO SMALLINT,
    PARTITA_IVA VARCHAR(32),
    CODICE_FISCALE VARCHAR(32),
    ACQUISIZIONE DATE,
    OPERATORE_ID CHAR(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_CLIENTI PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTI_OPERATORE FOREIGN KEY (OPERATORE_ID) REFERENCES OPERATORI (ID) ON DELETE SET NULL,
    CONSTRAINT CK_CLIENTI_COINVOLGIMENTO CHECK (COINVOLGIMENTO IS NULL OR (COINVOLGIMENTO >= 1 AND COINVOLGIMENTO <= 5))
);

CREATE TABLE CLIENTI_FORNI (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    FORNO_ID CHAR(36) NOT NULL,
    ANNO VARCHAR(20),
    NOTA VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_CLIENTI_FORNI PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTI_FORNI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CLIENTI_FORNI_FORNO FOREIGN KEY (FORNO_ID) REFERENCES FORNI (ID) ON DELETE CASCADE
);

CREATE TABLE CLIENTI_FRESATORI (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    FRESATORE_ID CHAR(36) NOT NULL,
    NOTA VARCHAR(500),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_CLIENTI_FRESATORI PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTI_FRESATORI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CLIENTI_FRESATORI_FRESATORE FOREIGN KEY (FRESATORE_ID) REFERENCES FRESATORI (ID) ON DELETE CASCADE
);

CREATE TABLE CLIENTI_MATERIALI (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    MATERIALE_ID CHAR(36) NOT NULL,
    NOTA VARCHAR(500),
    CONSUMO VARCHAR(120),
    FREQUENZA_ACQUISTO VARCHAR(120),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_CLIENTI_MATERIALI PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTI_MATERIALI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CLIENTI_MATERIALI_MATERIALE FOREIGN KEY (MATERIALE_ID) REFERENCES MATERIALI_DI_CONSUMO (ID) ON DELETE CASCADE
);

CREATE TABLE CLIENTI_PREFERITI (
    OPERATORE_ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    CONSTRAINT PK_CLIENTI_PREFERITI PRIMARY KEY (OPERATORE_ID, CLIENTE_ID),
    CONSTRAINT FK_CLIENTI_PREFERITI_OPERATORE FOREIGN KEY (OPERATORE_ID) REFERENCES OPERATORI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CLIENTI_PREFERITI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE
);

CREATE TABLE CONTATTI_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    DESCRIZIONE VARCHAR(255),
    CONSTRAINT PK_CONTATTI_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_CONTATTI_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE
);

CREATE TABLE INDIRIZZI_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    PAESE VARCHAR(80),
    REGIONE VARCHAR(80),
    PROVINCIA VARCHAR(20),
    CITTA VARCHAR(120),
    INDIRIZZO VARCHAR(255),
    NUMERO_CIVICO VARCHAR(30),
    CAP VARCHAR(20),
    PRINCIPALE SMALLINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_INDIRIZZI_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_INDIRIZZI_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT CK_INDIRIZZI_CLIENTE_PRINCIPALE CHECK (PRINCIPALE IN (0, 1))
);

CREATE TABLE TELEFONI_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    CONTATTO_ID CHAR(36),
    DESCRIZIONE VARCHAR(255),
    CONSTRAINT PK_TELEFONI_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_TELEFONI_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TELEFONI_CLIENTE_CONTATTO FOREIGN KEY (CONTATTO_ID) REFERENCES CONTATTI_CLIENTE (ID) ON DELETE CASCADE
);

CREATE TABLE EMAIL_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    CONTATTO_ID CHAR(36),
    DESCRIZIONE VARCHAR(255),
    CONSTRAINT PK_EMAIL_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_EMAIL_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMAIL_CLIENTE_CONTATTO FOREIGN KEY (CONTATTO_ID) REFERENCES CONTATTI_CLIENTE (ID) ON DELETE CASCADE
);

CREATE TABLE SITI_WEB_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    DESCRIZIONE VARCHAR(255),
    CONSTRAINT PK_SITI_WEB_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_SITI_WEB_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE
);

CREATE TABLE NOTE_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    OPERATORE_ID CHAR(36),
    TESTO CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_NOTE_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_NOTE_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTE_CLIENTE_OPERATORE FOREIGN KEY (OPERATORE_ID) REFERENCES OPERATORI (ID) ON DELETE SET NULL
);

CREATE TABLE INTERAZIONI (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    OPERATORE_ID CHAR(36),
    NOTA_ID CHAR(36),
    DATA_CONTATTO DATE,
    PROSSIMO_CONTATTO DATE,
    COINVOLGIMENTO DECIMAL(5, 2),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_INTERAZIONI PRIMARY KEY (ID),
    CONSTRAINT FK_INTERAZIONI_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_INTERAZIONI_OPERATORE FOREIGN KEY (OPERATORE_ID) REFERENCES OPERATORI (ID) ON DELETE SET NULL,
    CONSTRAINT FK_INTERAZIONI_NOTA FOREIGN KEY (NOTA_ID) REFERENCES NOTE_CLIENTE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_INTERAZIONI_COINVOLGIMENTO CHECK (COINVOLGIMENTO >= 0 AND COINVOLGIMENTO <= 100)
);

CREATE INDEX IX_TIPI_CLIENTE_ORDINE ON TIPI_CLIENTE (ORDINE, NOME);
CREATE INDEX IX_STATI_TRATTATIVA_ORDINE ON STATI_TRATTATIVA (ORDINE, NOME);
CREATE INDEX IX_CLIENTI_RAGIONE_SOCIALE ON CLIENTI (RAGIONE_SOCIALE);
CREATE INDEX IX_CLIENTI_TIPO_CLIENTE ON CLIENTI (TIPO_CLIENTE);
CREATE INDEX IX_CLIENTI_STATO_TRATTATIVA ON CLIENTI (STATO_TRATTATIVA);
CREATE INDEX IX_CLIENTI_FORNI_CLIENTE ON CLIENTI_FORNI (CLIENTE_ID);
CREATE INDEX IX_CLIENTI_FORNI_FORNO ON CLIENTI_FORNI (FORNO_ID);
CREATE INDEX IX_CLIENTI_FRESATORI_CLIENTE ON CLIENTI_FRESATORI (CLIENTE_ID);
CREATE INDEX IX_CLIENTI_FRESATORI_FRESATORE ON CLIENTI_FRESATORI (FRESATORE_ID);
CREATE INDEX IX_CLIENTI_MATERIALI_CLIENTE ON CLIENTI_MATERIALI (CLIENTE_ID);
CREATE INDEX IX_CLIENTI_MATERIALI_MATERIALE ON CLIENTI_MATERIALI (MATERIALE_ID);
CREATE INDEX IX_CLIENTI_PREFERITI_CLIENTE ON CLIENTI_PREFERITI (CLIENTE_ID);
CREATE INDEX IX_CONTATTI_CLIENTE_CLIENTE ON CONTATTI_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_INDIRIZZI_CLIENTE_CLIENTE ON INDIRIZZI_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_TELEFONI_CLIENTE_CLIENTE ON TELEFONI_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_TELEFONI_CLIENTE_CONTATTO ON TELEFONI_CLIENTE (CONTATTO_ID);
CREATE INDEX IX_EMAIL_CLIENTE_CLIENTE ON EMAIL_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_EMAIL_CLIENTE_CONTATTO ON EMAIL_CLIENTE (CONTATTO_ID);
CREATE INDEX IX_SITI_WEB_CLIENTE_CLIENTE ON SITI_WEB_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_NOTE_CLIENTE_CLIENTE ON NOTE_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_INTERAZIONI_CLIENTE ON INTERAZIONI (CLIENTE_ID);
CREATE INDEX IX_INTERAZIONI_PROSSIMO ON INTERAZIONI (PROSSIMO_CONTATTO);
