-- Schema iniziale per la feature Clienti.
-- Pensato per Apache Derby: gli UUID vengono salvati come CHAR(36) e generati dall'applicazione.
-- Il file non usa CREATE TABLE IF NOT EXISTS perché Derby non lo supporta in modo portabile.

CREATE TABLE OPERATORI (
    ID CHAR(36) NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    COGNOME VARCHAR(120),
    USERNAME VARCHAR(80),
    ATTIVO SMALLINT DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_OPERATORI PRIMARY KEY (ID),
    CONSTRAINT UQ_OPERATORI_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_OPERATORI_ATTIVO CHECK (ATTIVO IN (0, 1))
);

CREATE TABLE CLIENTI (
    ID CHAR(36) NOT NULL,
    RAGIONE_SOCIALE VARCHAR(255) NOT NULL,
    TIPO_CLIENTE VARCHAR(40) NOT NULL,
    INTERESSAMENTO VARCHAR(40) NOT NULL,
    PARTITA_IVA VARCHAR(32),
    CODICE_FISCALE VARCHAR(32),
    TITOLARE VARCHAR(180),
    SITO_WEB VARCHAR(255),
    COINVOLGIMENTO DECIMAL(5, 2) DEFAULT 0 NOT NULL,
    CHECKPOINT_STEP INTEGER DEFAULT 0 NOT NULL,
    ACQUISIZIONE DATE,
    VOLTE_CONTATTATI INTEGER DEFAULT 0 NOT NULL,
    ULTIMA_CHIAMATA DATE,
    PROSSIMA_CHIAMATA DATE,
    OPERATORE_ID CHAR(36),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_CLIENTI PRIMARY KEY (ID),
    CONSTRAINT FK_CLIENTI_OPERATORE FOREIGN KEY (OPERATORE_ID) REFERENCES OPERATORI (ID) ON DELETE SET NULL,
    CONSTRAINT CK_CLIENTI_COINVOLGIMENTO CHECK (COINVOLGIMENTO >= 0 AND COINVOLGIMENTO <= 100),
    CONSTRAINT CK_CLIENTI_CHECKPOINT CHECK (CHECKPOINT_STEP >= 0),
    CONSTRAINT CK_CLIENTI_VOLTE_CONTATTATI CHECK (VOLTE_CONTATTATI >= 0)
);

CREATE TABLE CONTATTI_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    NOME VARCHAR(120),
    COGNOME VARCHAR(120),
    NOME_VISUALIZZATO VARCHAR(255) NOT NULL,
    RUOLO VARCHAR(80),
    PRINCIPALE SMALLINT DEFAULT 0 NOT NULL,
    NOTE VARCHAR(1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_CONTATTI_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_CONTATTI_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT CK_CONTATTI_CLIENTE_PRINCIPALE CHECK (PRINCIPALE IN (0, 1))
);

CREATE TABLE INDIRIZZI_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    TIPO VARCHAR(40) DEFAULT 'PRINCIPALE' NOT NULL,
    PAESE VARCHAR(80),
    REGIONE VARCHAR(80),
    PROVINCIA VARCHAR(20),
    CITTA VARCHAR(120),
    INDIRIZZO VARCHAR(255),
    NUMERO_CIVICO VARCHAR(30),
    CAP VARCHAR(20),
    PRINCIPALE SMALLINT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_INDIRIZZI_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_INDIRIZZI_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT CK_INDIRIZZI_CLIENTE_PRINCIPALE CHECK (PRINCIPALE IN (0, 1))
);

CREATE TABLE TELEFONI_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36),
    CONTATTO_ID CHAR(36),
    NUMERO VARCHAR(50) NOT NULL,
    TIPO VARCHAR(40) DEFAULT 'ALTRO' NOT NULL,
    PRINCIPALE SMALLINT DEFAULT 0 NOT NULL,
    DESCRIZIONE VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_TELEFONI_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_TELEFONI_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_TELEFONI_CLIENTE_CONTATTO FOREIGN KEY (CONTATTO_ID) REFERENCES CONTATTI_CLIENTE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_TELEFONI_CLIENTE_OWNER CHECK (
        (CLIENTE_ID IS NOT NULL AND CONTATTO_ID IS NULL)
        OR (CLIENTE_ID IS NULL AND CONTATTO_ID IS NOT NULL)
    ),
    CONSTRAINT CK_TELEFONI_CLIENTE_PRINCIPALE CHECK (PRINCIPALE IN (0, 1))
);

CREATE TABLE EMAIL_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36),
    CONTATTO_ID CHAR(36),
    EMAIL VARCHAR(255) NOT NULL,
    TIPO VARCHAR(40) DEFAULT 'ALTRO' NOT NULL,
    PRINCIPALE SMALLINT DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_EMAIL_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_EMAIL_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_EMAIL_CLIENTE_CONTATTO FOREIGN KEY (CONTATTO_ID) REFERENCES CONTATTI_CLIENTE (ID) ON DELETE CASCADE,
    CONSTRAINT CK_EMAIL_CLIENTE_OWNER CHECK (
        (CLIENTE_ID IS NOT NULL AND CONTATTO_ID IS NULL)
        OR (CLIENTE_ID IS NULL AND CONTATTO_ID IS NOT NULL)
    ),
    CONSTRAINT CK_EMAIL_CLIENTE_PRINCIPALE CHECK (PRINCIPALE IN (0, 1))
);

CREATE TABLE ATTIVITA_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    CONTATTO_ID CHAR(36),
    OPERATORE_ID CHAR(36),
    TIPO VARCHAR(40) NOT NULL,
    DATA_ATTIVITA DATE NOT NULL,
    ESITO VARCHAR(80),
    PROSSIMA_ATTIVITA DATE,
    NOTE VARCHAR(2000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_ATTIVITA_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_ATTIVITA_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ATTIVITA_CLIENTE_CONTATTO FOREIGN KEY (CONTATTO_ID) REFERENCES CONTATTI_CLIENTE (ID) ON DELETE SET NULL,
    CONSTRAINT FK_ATTIVITA_CLIENTE_OPERATORE FOREIGN KEY (OPERATORE_ID) REFERENCES OPERATORI (ID) ON DELETE SET NULL
);

CREATE TABLE NOTE_CLIENTE (
    ID CHAR(36) NOT NULL,
    CLIENTE_ID CHAR(36) NOT NULL,
    OPERATORE_ID CHAR(36),
    TESTO CLOB NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_NOTE_CLIENTE PRIMARY KEY (ID),
    CONSTRAINT FK_NOTE_CLIENTE_CLIENTE FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTI (ID) ON DELETE CASCADE,
    CONSTRAINT FK_NOTE_CLIENTE_OPERATORE FOREIGN KEY (OPERATORE_ID) REFERENCES OPERATORI (ID) ON DELETE SET NULL
);

CREATE INDEX IX_CLIENTI_RAGIONE_SOCIALE ON CLIENTI (RAGIONE_SOCIALE);
CREATE INDEX IX_CLIENTI_TIPO_CLIENTE ON CLIENTI (TIPO_CLIENTE);
CREATE INDEX IX_CLIENTI_INTERESSAMENTO ON CLIENTI (INTERESSAMENTO);
CREATE INDEX IX_CLIENTI_PROSSIMA_CHIAMATA ON CLIENTI (PROSSIMA_CHIAMATA);
CREATE INDEX IX_CONTATTI_CLIENTE_CLIENTE ON CONTATTI_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_INDIRIZZI_CLIENTE_CLIENTE ON INDIRIZZI_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_TELEFONI_CLIENTE_CLIENTE ON TELEFONI_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_TELEFONI_CLIENTE_CONTATTO ON TELEFONI_CLIENTE (CONTATTO_ID);
CREATE INDEX IX_EMAIL_CLIENTE_CLIENTE ON EMAIL_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_EMAIL_CLIENTE_CONTATTO ON EMAIL_CLIENTE (CONTATTO_ID);
CREATE INDEX IX_ATTIVITA_CLIENTE_CLIENTE ON ATTIVITA_CLIENTE (CLIENTE_ID);
CREATE INDEX IX_ATTIVITA_CLIENTE_PROSSIMA ON ATTIVITA_CLIENTE (PROSSIMA_ATTIVITA);
CREATE INDEX IX_NOTE_CLIENTE_CLIENTE ON NOTE_CLIENTE (CLIENTE_ID);
